# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LLEgZB-TQZZHlYNJp_BGQX8yNWjkBESx
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm
import nltk

plt.style.use("ggplot")


# nltk.download("stopwords")
# nltk.download("wordnet")
# nltk.download("punkt")
# nltk.download("averaged_perceptron_tagger")
# nltk.download("maxent_ne_chunker")
# nltk.download("words")
# nltk.download("vader_lexicon")


def analyze_text():
    df = pd.read_csv("./posts.csv")

    # ax = df['upvote_ratio'].value_counts().sort_index().plot(kind='bar', title='Upvote ratio', figsize=(10, 5))
    # ax.set_xlabel('Ratio')
    # plt.show()

    sia = SentimentIntensityAnalyzer()

    res = {}
    for i, row in df.iterrows():
        text = row["title"] + row["selftext"]
        res[i] = sia.polarity_scores(text)

    vaders = pd.DataFrame(res).T
    vaders = vaders.reset_index().rename(columns={"index": "ID"})
    vaders = vaders.merge(df, how="left")

    file_path = "vader.csv"
    vaders.to_csv(file_path, index=False)

    # fig, axs = plt.subplots(1, 3, figsize=(12, 3))
    # sns.barplot(data=vaders, x="upvote_ratio", y="pos", ax=axs[0])
    # sns.barplot(data=vaders, x="upvote_ratio", y="neu", ax=axs[1])
    # sns.barplot(data=vaders, x="upvote_ratio", y="neg", ax=axs[2])

    # axs[0].set_title("Positive")
    # axs[1].set_title("Neutral")
    # axs[2].set_title("Negative")

    # plt.show()


analyze_text()
