TOP_CRYPTO_TUPLES = [
    ("Bitcoin", "btc"),
    ("Ethereum", "eth"),
    ("Tether", "usdt"),
    ("BNB", "bnb"),
    ("Solana", "sol"),
    ("XRP", "xrp"),
    # ("USDC", "usdc"),
    ("Lido Staked Ether", "steth"),
    ("Cardano", "ada"),
    ("Avalanche", "avax"),
    ("Dogecoin", "doge"),
    ("TRON", "trx"),
    ("Polkadot", "dot"),
    ("Chainlink", "link"),
    # ("Toncoin", "ton"),
    ("Polygon", "matic"),
    ("Wrapped Bitcoin", "wbtc"),
    ("Internet Computer", "icp"),
    ("Shiba Inu", "shib"),
    ("Dai", "dai"),
    ("Litecoin", "ltc"),
    ("Bitcoin Cash", "bch"),
    ("Uniswap", "uni"),
    ("LEO Token", "leo"),
    ("Cosmos Hub", "atom"),
    ("Ethereum Classic", "etc"),
    ("Stellar", "xlm"),
    ("OKB", "okb"),
    ("NEAR Protocol", "near"),
    ("Injective", "inj"),
    ("Optimism", "op"),
    ("Aptos", "apt"),
    # ("Monero", "xmr"),
    ("Lido DAO", "ldo"),
    ("Celestia", "tia"),
    ("First Digital USD", "fdusd"),
    ("Filecoin", "fil"),
    ("Immutable", "imx"),
    ("Hedera", "hbar"),
    ("Kaspa", "kas"),
    ("Arbitrum", "arb"),
    ("Stacks", "stx"),
    ("Cronos", "cro"),
    ("Bittensor", "tao"),
    ("Mantle", "mnt"),
    ("VeChain", "vet"),
    ("Maker", "mkr"),
    # ("TrueUSD", "tusd"),
    ("Quant", "qnt"),
    ("Sei", "sei"),
    ("Render", "rndr"),
    ("The Graph", "grt"),
    ("Sui", "sui"),
    ("Rocket Pool ETH", "reth"),
    ("Bitcoin SV", "bsv"),
    ("MultiversX", "egld"),
    ("Algorand", "algo"),
    ("Aave", "aave"),
    # ("THORChain", "rune"),
    ("ORDI", "ordi"),
    ("Flow", "flow"),
    ("Mina Protocol", "mina"),
    ("Synthetix Network", "snx"),
    ("Helium", "hnt"),
    ("The Sandbox", "sand"),
    ("Chiliz", "chz"),
    ("dYdX", "dydx"),
    ("Tokenize Xchange", "tkx"),
    ("Fantom", "ftm"),
    ("Axie Infinity", "axs"),
    ("Theta Network", "theta"),
    # ("KuCoin", "kcs"),
    ("Osmosis", "osmo"),
    # ("SATS (Ordinals)", "sats"),
    ("Astar", "astr"),
    ("WhiteBIT Coin", "wbt"),
    ("Beam", "beam"),
    ("Tezos", "xtz"),
    ("WEMIX", "wemix"),
    ("Cheelee", "cheel"),
    ("dYdX", "ethdydx"),
    ("ApeCoin", "ape"),
    ("Decentraland", "mana"),
    ("BitTorrent", "btt"),
    ("Bitget Token", "bgb"),
    ("EOS", "eos"),
    ("Blur", "blur"),
    ("Frax Share", "fxs"),
    # ("Manta Network", "manta"),
    ("Conflux", "cfx"),
    ("NEO", "neo"),
    ("IOTA", "iota"),
    ("Kava", "kava"),
    ("GALA", "gala"),
    ("USDD", "usdd"),
    ("Bonk", "bonk"),
    ("Klaytn", "klay"),
    ("Oasis Network", "rose"),
    ("Frax Ether", "frxeth"),
    ("Flare", "flr"),
]

TOP_CRYPTO_LIST = [
    "Bitcoin",
    "btc",
    "Ethereum",
    "eth",
    "Tether",
    "usdt",
    "BNB",
    "bnb",
    "Solana",
    "sol",
    "XRP",
    "xrp",
    # "USDC",
    # "usdc",
    "Lido Staked Ether",
    "steth",
    "Cardano",
    "ada",
    "Avalanche",
    "avax",
    "Dogecoin",
    "doge",
    "TRON",
    "trx",
    "Polkadot",
    "dot",
    "Chainlink",
    "link",
    # "Toncoin",
    # "ton",
    "Polygon",
    "matic",
    "Wrapped Bitcoin",
    "wbtc",
    "Internet Computer",
    "icp",
    "Shiba Inu",
    "shib",
    "Dai",
    "dai",
    "Litecoin",
    "ltc",
    "Bitcoin Cash",
    "bch",
    "Uniswap",
    "uni",
    "LEO Token",
    "leo",
    "Cosmos Hub",
    "atom",
    "Ethereum Classic",
    "etc",
    "Stellar",
    "xlm",
    "OKB",
    "okb",
    "NEAR Protocol",
    "near",
    "Injective",
    "inj",
    "Optimism",
    "op",
    "Aptos",
    "apt",
    # "Monero",
    # "xmr",
    "Lido DAO",
    "ldo",
    "Celestia",
    "tia",
    "First Digital USD",
    "fdusd",
    "Filecoin",
    "fil",
    "Immutable",
    "imx",
    "Hedera",
    "hbar",
    "Kaspa",
    "kas",
    "Arbitrum",
    "arb",
    "Stacks",
    "stx",
    "Cronos",
    "cro",
    "Bittensor",
    "tao",
    "Mantle",
    "mnt",
    "VeChain",
    "vet",
    "Maker",
    "mkr",
    # "TrueUSD",
    # "tusd",
    "Quant",
    "qnt",
    "Sei",
    "sei",
    "Render",
    "rndr",
    "The Graph",
    "grt",
    "Sui",
    "sui",
    "Rocket Pool ETH",
    "reth",
    "Bitcoin SV",
    "bsv",
    "MultiversX",
    "egld",
    "Algorand",
    "algo",
    "Aave",
    "aave",
    # "THORChain",
    # "rune",
    "ORDI",
    "ordi",
    "Flow",
    "flow",
    "Mina Protocol",
    "mina",
    "Synthetix Network",
    "snx",
    "Helium",
    "hnt",
    "The Sandbox",
    "sand",
    "Chiliz",
    "chz",
    "dYdX",
    "dydx",
    "Tokenize Xchange",
    "tkx",
    "Fantom",
    "ftm",
    "Axie Infinity",
    "axs",
    "Theta Network",
    "theta",
    # "KuCoin",
    # "kcs",
    "Osmosis",
    "osmo",
    # "SATS (Ordinals)",
    # "sats",
    "Astar",
    "astr",
    "WhiteBIT Coin",
    "wbt",
    "Beam",
    "beam",
    "Tezos",
    "xtz",
    "WEMIX",
    "wemix",
    "Cheelee",
    "cheel",
    "dYdX (ethdydx)",
    "ethdydx",
    "ApeCoin",
    "ape",
    "Decentraland",
    "mana",
    "BitTorrent",
    "btt",
    "Bitget Token",
    "bgb",
    "EOS",
    "eos",
    "Blur",
    "blur",
    "Frax Share",
    "fxs",
    # "Manta Network",
    # "manta",
    "Conflux",
    "cfx",
    "NEO",
    "neo",
    "IOTA",
    "iota",
    "Kava",
    "kava",
    "GALA",
    "gala",
    "USDD",
    "usdd",
    "Bonk",
    "bonk",
    "Klaytn",
    "klay",
    "Oasis Network",
    "rose",
    "Frax Ether",
    "frxeth",
    "Flare",
    "flr",
]
